<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="forklift">

  <!-- ==================== PROPERTIES ==================== -->
  <xacro:property name="chassis_length" value="1.0"/>
  <xacro:property name="chassis_width" value="0.6"/>
  <xacro:property name="chassis_height" value="0.2"/>
  <xacro:property name="chassis_mass" value="10.0"/>

  <xacro:property name="wheel_radius" value="0.15"/>
  <xacro:property name="wheel_width" value="0.05"/>
  <xacro:property name="wheel_mass" value="2.0"/>
  <xacro:property name="wheel_separation" value="0.5"/>

  <xacro:property name="caster_radius" value="0.05"/>
  <xacro:property name="caster_mass" value="0.5"/>

  <xacro:property name="lidar_radius" value="0.05"/>
  <xacro:property name="lidar_height" value="0.08"/>
  <xacro:property name="lidar_mass" value="0.3"/>

  <xacro:property name="camera_size" value="0.05"/>
  <xacro:property name="camera_mass" value="0.1"/>

  <xacro:property name="fork_length" value="0.8"/>
  <xacro:property name="fork_width" value="0.08"/>
  <xacro:property name="fork_height" value="0.03"/>
  <xacro:property name="fork_separation" value="0.3"/>

  <!-- ==================== INERTIA MACROS ==================== -->
  <xacro:macro name="box_inertia" params="m x y z">
    <inertial>
      <mass value="${m}"/>
      <inertia ixx="${(m/12)*(y*y+z*z)}" ixy="0" ixz="0"
               iyy="${(m/12)*(x*x+z*z)}" iyz="0"
               izz="${(m/12)*(x*x+y*y)}"/>
    </inertial>
  </xacro:macro>

  <xacro:macro name="cylinder_inertia" params="m r h">
    <inertial>
      <mass value="${m}"/>
      <inertia ixx="${(m/12)*(3*r*r+h*h)}" ixy="0" ixz="0"
               iyy="${(m/12)*(3*r*r+h*h)}" iyz="0"
               izz="${(m/2)*r*r}"/>
    </inertial>
  </xacro:macro>

  <xacro:macro name="sphere_inertia" params="m r">
    <inertial>
      <mass value="${m}"/>
      <inertia ixx="${(2/5)*m*r*r}" ixy="0" ixz="0"
               iyy="${(2/5)*m*r*r}" iyz="0"
               izz="${(2/5)*m*r*r}"/>
    </inertial>
  </xacro:macro>

  <!-- ==================== BASE LINK ==================== -->
  <link name="base_footprint"/>

  <joint name="base_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link"/>
    <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0"/>
  </joint>

  <link name="base_link">
    <visual>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
      <material name="orange">
        <color rgba="1.0 0.5 0.0 1.0"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
    </collision>
    <xacro:box_inertia m="${chassis_mass}" x="${chassis_length}" y="${chassis_width}" z="${chassis_height}"/>
  </link>

  <!-- ==================== DRIVE WHEELS (FRONT) ==================== -->
  <xacro:macro name="drive_wheel" params="prefix y_offset">
    <link name="${prefix}_wheel_link">
      <visual>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
        <material name="black">
          <color rgba="0.1 0.1 0.1 1.0"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
      </collision>
      <xacro:cylinder_inertia m="${wheel_mass}" r="${wheel_radius}" h="${wheel_width}"/>
    </link>

    <joint name="${prefix}_wheel_joint" type="continuous">
      <parent link="base_link"/>
      <child link="${prefix}_wheel_link"/>
      <origin xyz="${chassis_length/2 - wheel_radius} ${y_offset} 0" rpy="${-pi/2} 0 0"/>
      <axis xyz="0 0 1"/>
      <limit effort="1000.0" velocity="20.0"/>
    </joint>
  </xacro:macro>

  <xacro:drive_wheel prefix="left" y_offset="${wheel_separation/2}"/>
  <xacro:drive_wheel prefix="right" y_offset="${-wheel_separation/2}"/>

  <!-- ==================== CASTER WHEEL (REAR) ==================== -->
  <link name="caster_wheel_link">
    <visual>
      <geometry>
        <sphere radius="${caster_radius}"/>
      </geometry>
      <material name="gray">
        <color rgba="0.5 0.5 0.5 1.0"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <sphere radius="${caster_radius}"/>
      </geometry>
    </collision>
    <xacro:sphere_inertia m="${caster_mass}" r="${caster_radius}"/>
  </link>

  <joint name="caster_wheel_joint" type="fixed">
    <parent link="base_link"/>
    <child link="caster_wheel_link"/>
    <origin xyz="${-chassis_length/2 + caster_radius} 0 ${-wheel_radius + caster_radius}" rpy="0 0 0"/>
  </joint>

  <!-- ==================== LIDAR ==================== -->
  <link name="lidar_link">
    <visual>
      <geometry>
        <cylinder radius="${lidar_radius}" length="${lidar_height}"/>
      </geometry>
      <material name="blue">
        <color rgba="0.0 0.0 0.8 1.0"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${lidar_radius}" length="${lidar_height}"/>
      </geometry>
    </collision>
    <xacro:cylinder_inertia m="${lidar_mass}" r="${lidar_radius}" h="${lidar_height}"/>
  </link>

  <joint name="lidar_joint" type="fixed">
    <parent link="base_link"/>
    <child link="lidar_link"/>
    <origin xyz="0 0 ${chassis_height/2 + lidar_height/2}" rpy="0 0 0"/>
  </joint>

  <!-- ==================== CAMERA ==================== -->
  <link name="camera_link">
    <visual>
      <geometry>
        <box size="${camera_size} ${camera_size*2} ${camera_size}"/>
      </geometry>
      <material name="red">
        <color rgba="0.8 0.0 0.0 1.0"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <box size="${camera_size} ${camera_size*2} ${camera_size}"/>
      </geometry>
    </collision>
    <xacro:box_inertia m="${camera_mass}" x="${camera_size}" y="${camera_size*2}" z="${camera_size}"/>
  </link>

  <joint name="camera_joint" type="fixed">
    <parent link="base_link"/>
    <child link="camera_link"/>
    <origin xyz="${chassis_length/2 + camera_size/2} 0 ${chassis_height/4}" rpy="0 0 0"/>
  </joint>

  <link name="camera_optical_frame"/>
  <joint name="camera_optical_joint" type="fixed">
    <parent link="camera_link"/>
    <child link="camera_optical_frame"/>
    <origin xyz="0 0 0" rpy="${-pi/2} 0 ${-pi/2}"/>
  </joint>

  <!-- ==================== FORKS (VISUAL ONLY) ==================== -->
  <xacro:macro name="fork" params="prefix y_offset">
    <link name="${prefix}_fork_link">
      <visual>
        <geometry>
          <box size="${fork_length} ${fork_width} ${fork_height}"/>
        </geometry>
        <material name="silver">
          <color rgba="0.7 0.7 0.7 1.0"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <box size="${fork_length} ${fork_width} ${fork_height}"/>
        </geometry>
      </collision>
      <xacro:box_inertia m="1.0" x="${fork_length}" y="${fork_width}" z="${fork_height}"/>
    </link>

    <joint name="${prefix}_fork_joint" type="fixed">
      <parent link="base_link"/>
      <child link="${prefix}_fork_link"/>
      <origin xyz="${chassis_length/2 + fork_length/2} ${y_offset} ${-chassis_height/2 + fork_height/2}" rpy="0 0 0"/>
    </joint>
  </xacro:macro>

  <xacro:fork prefix="left" y_offset="${fork_separation/2}"/>
  <xacro:fork prefix="right" y_offset="${-fork_separation/2}"/>

  <!-- ==================== GAZEBO PLUGINS ==================== -->
  
  <!-- Differential Drive Controller -->
  <gazebo>
    <plugin filename="gz-sim-diff-drive-system" name="gz::sim::systems::DiffDrive">
      <left_joint>left_wheel_joint</left_joint>
      <right_joint>right_wheel_joint</right_joint>
      <wheel_separation>${wheel_separation}</wheel_separation>
      <wheel_radius>${wheel_radius}</wheel_radius>
      <odom_publish_frequency>50</odom_publish_frequency>
      <max_linear_acceleration>4.0</max_linear_acceleration>
      <min_linear_acceleration>-4.0</min_linear_acceleration>
      <max_angular_acceleration>4.0</max_angular_acceleration>
      <min_angular_acceleration>-4.0</min_angular_acceleration>
      <max_linear_velocity>10.0</max_linear_velocity>
      <min_linear_velocity>-10.0</min_linear_velocity>
      <max_angular_velocity>10.0</max_angular_velocity>
      <min_angular_velocity>-10.0</min_angular_velocity>
      <topic>/cmd_vel</topic>
      <odom_topic>odom</odom_topic>
      <tf_topic>tf</tf_topic>
      <frame_id>odom</frame_id>
      <child_frame_id>base_footprint</child_frame_id>
    </plugin>
  </gazebo>

  <!-- Joint State Publisher -->
  <gazebo>
    <plugin filename="gz-sim-joint-state-publisher-system" name="gz::sim::systems::JointStatePublisher">
      <topic>joint_states</topic>
      <joint_name>left_wheel_joint</joint_name>
      <joint_name>right_wheel_joint</joint_name>
    </plugin>
  </gazebo>

  <!-- Sensors Plugin -->
  <gazebo>
    <plugin filename="gz-sim-sensors-system" name="gz::sim::systems::Sensors">
      <render_engine>ogre2</render_engine>
    </plugin>
  </gazebo>

  <!-- Lidar Sensor -->
  <gazebo reference="lidar_link">
    <sensor name="lidar" type="gpu_lidar">
      <topic>scan</topic>
      <update_rate>5</update_rate>
      <lidar>
        <scan>
          <horizontal>
            <samples>360</samples>
            <resolution>1</resolution>
            <min_angle>-3.14159</min_angle>
            <max_angle>3.14159</max_angle>
          </horizontal>
        </scan>
        <range>
          <min>0.1</min>
          <max>12.0</max>
          <resolution>0.01</resolution>
        </range>
      </lidar>
      <always_on>true</always_on>
      <visualize>false</visualize>
    </sensor>
  </gazebo>

  <!-- Camera Sensor -->
  <gazebo reference="camera_link">
    <sensor name="camera" type="camera">
      <topic>/camera_sensor/image_raw</topic>
      <update_rate>5</update_rate>
      <camera>
        <horizontal_fov>1.047</horizontal_fov>
        <image>
          <width>320</width>
          <height>240</height>
          <format>R8G8B8</format>
        </image>
        <clip>
          <near>0.1</near>
          <far>100</far>
        </clip>
      </camera>
      <always_on>true</always_on>
      <visualize>false</visualize>
    </sensor>
  </gazebo>

  <!-- Headlight (Spotlight) -->
  <gazebo reference="camera_link">
    <light name="headlight" type="spot">
      <pose>0 0 0 0 0 0</pose>
      <diffuse>1 1 1 1</diffuse>
      <specular>1 1 1 1</specular>
      <direction>1 0 0</direction>
      <attenuation>
        <range>20</range>
        <constant>0.5</constant>
        <linear>0.01</linear>
        <quadratic>0.001</quadratic>
      </attenuation>
      <spot>
        <inner_angle>0.6</inner_angle>
        <outer_angle>1.0</outer_angle>
        <falloff>1.0</falloff>
      </spot>
      <cast_shadows>true</cast_shadows>
    </light>
  </gazebo>

  <!-- Caster wheel friction (frictionless for smooth movement) -->
  <gazebo reference="caster_wheel_link">
    <mu1>0.0</mu1>
    <mu2>0.0</mu2>
  </gazebo>

  <gazebo reference="left_wheel_link">
    <mu1>1.0</mu1>
    <mu2>1.0</mu2>
  </gazebo>

  <gazebo reference="right_wheel_link">
    <mu1>1.0</mu1>
    <mu2>1.0</mu2>
  </gazebo>

</robot>
